name: Keep Render API Alive

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -I https://ladder-ai.onrender.com
